/** @type {import('tailwindcss').Config} */
export default {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}", "./htmls/**/*.html"],
    theme: {
        extend: {
            colors: {
                "error-dim": "#b92902",
                "on-secondary-fixed-variant": "#950085",
                "surface-tint": "#4f6300",
                "inverse-surface": "#0e0e0e",
                "on-surface": "#2f2e2e",
                "on-primary": "#e2ff82",
                "primary": "#4f6300",
                "surface-container-highest": "#dfdcdc",
                "surface-variant": "#dfdcdc",
                "background": "#f9f6f5",
                "outline": "#787676",
                "tertiary-fixed-dim": "#00deec",
                "tertiary-dim": "#00595f",
                "on-surface-variant": "#5c5b5b",
                "surface-container-high": "#e5e2e1",
                "error": "#b02500",
                "on-primary-container": "#4b5e00",
                "on-error-container": "#520c00",
                "outline-variant": "#afacac",
                "primary-fixed": "#cefc00",
                "tertiary": "#00666d",
                "on-primary-fixed-variant": "#546800",
                "inverse-primary": "#cefc00",
                "surface-container-lowest": "#ffffff",
                "secondary-fixed": "#ffbeeb",
                "error-container": "#f95630",
                "surface": "#f9f6f5",
                "on-secondary-fixed": "#640059",
                "surface-container": "#eae7e7",
                "primary-fixed-dim": "#c1ed00",
                "tertiary-fixed": "#00eefc",
                "surface-dim": "#d6d4d3",
                "secondary": "#a80096",
                "secondary-dim": "#940084",
                "inverse-on-surface": "#9e9c9c",
                "on-tertiary-container": "#005359",
                "secondary-container": "#ffbeeb",
                "on-tertiary-fixed-variant": "#005e64",
                "surface-bright": "#f9f6f5",
                "on-error": "#ffefec",
                "primary-dim": "#455600",
                "secondary-fixed-dim": "#ffa8e7",
                "on-secondary-container": "#850077",
                "on-background": "#2f2e2e",
                "surface-container-low": "#f3f0ef",
                "on-primary-fixed": "#3b4a00",
                "primary-container": "#cefc00",
                "on-secondary": "#ffeef6",
                "tertiary-container": "#00eefc",
                "on-tertiary-fixed": "#003f43",
                "on-tertiary": "#cffbff",
            },
            fontFamily: {
                "headline": ["Space Grotesk"],
                "body": ["Plus Jakarta Sans"],
                "label": ["Plus Jakarta Sans"],
            },
            borderRadius: {
                DEFAULT: "1rem",
                lg: "2rem",
                xl: "3rem",
                full: "9999px",
            },
        },
    },
    plugins: [],
};
